# Basic Information 
title: Ting Xu (徐婷)
position: 
affiliation: UESTC
affiliation_link: https://www.uestc.edu.cn/
email: E-mail: tingxu113@163.com

# Search Engine Optimization (SEO) 
keywords: Ting Xu, 徐婷
canonical: https://tingxu113.github.io/
description: Ting Xu is currently working toward the Ph.D. degree. Her research lies in image fusion.

# The option is used to enable the Johns Hopkins template.
enable_jhu_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
google_scholar: https://scholar.google.com/citations?user=NMwLfkYAAAAJ&hl=zh-CN&oi=sra
cv_link: 
github_link: https://github.com/tingxu113/
linkedin: 
twitter: 

# Images 
avatar: ./assets/img/ting.JPG
favicon: ./assets/img/uestc.png
favicon_dark: ./assets/img/uestc.png

# Footnotes
# footnote: Feel free to use my website's source code. 
# footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: l3lesztPwCz-uXlzFI1Lt9SB3Ctz-pBQuMdYqnD0Ul8

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
